require("plugins/setup")

require("utils")
require("keymaps")
require("settings")
require("autocmds")
require("icons")

require("plugins.colorscheme")
require("plugins.bufferline")
require("plugins.telescope")
require("plugins.null_ls")
require("plugins.lsp")
require("plugins.compe")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.comment")
require("plugins.lualine")
require("plugins.gitsigns")
require("plugins.hop")
require("plugins.nvim-tree")
require("plugins.impatient")
require("plugins.toggleterm")
require("plugins.transparent")
require("plugins.autopair")
