require("plugins/setup")

require("utils")
require("keymaps")
require("settings")
require("autocmds")
require('utils')
require('icons')

require("plugins.bufferline")
require("plugins.telescope")
require("plugins.lsp")
require("plugins.compe")
require("plugins.treesitter")
require("plugins.colorscheme")
require("plugins.telescope")
require("plugins.comment")
require("plugins.lualine")
require("plugins.gitsigns")
require("plugins.hop")
require("plugins.nvim-tree")
require("plugins.impatient")

