#!/usr/bin/env sh
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m rule --add title='^Window Title$' \
  sticky=off layer=above manage=off border=off

# global settings
# focus window that your mouse hovers on (disabled due to right click bugs)
yabai -m config focus_follows_mouse          off
# move mouse to focused window
yabai -m config mouse_follows_focus          off
yabai -m config window_placement             second_child
# floating windows always stay on top
yabai -m config window_topmost               on
# enable borders
yabai -m config window_border                on
# no clue what this is
# yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
# don't automatically rebalance windows
yabai -m config auto_balance                 on
# swap windows if moved with mouse
yabai -m config mouse_action1                move
# resize windows if resized with mouse
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   06

# SIP Required
# prevent border from being under the active window
yabai -m config active_window_border_topmost on
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_border_width          1
yabai -m config active_window_border_color 0xFF88C0D0
yabai -m config normal_window_border_color 0x002E3440
yabai -m config insert_feedback_color 0xFFA3BE8C
# yabai -m config active_window_border_color   0x8fa2a523
# yabai -m config normal_window_border_color   0x2fff3050

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config active_window_opacity 1
yabai -m config normal_window_opacity 0.98

# # bsp or float (default: float)
# yabai -m config layout bsp
#
# # Override default layout for space 2 only
# yabai -m config --space 2 layout float
#
# # New window spawns to the left if vertical split, or top if horizontal split
# yabai -m config window_placement first_child
#
# # New window spawns to the right if vertical split, or bottom if horizontal split
# yabai -m config window_placement second_child
#
# # Set all padding and gaps to 20pt (default: 0)
# yabai -m config top_padding    10
# yabai -m config bottom_padding 10
# yabai -m config left_padding   10
# yabai -m config right_padding  10
# yabai -m config window_gap     10
#
# # Override gaps for space 2 only
# # yabai -m config --space 2 window_gap
#
# # on or off (default: off)
# yabai -m config auto_balance off
#
# # Floating point value between 0 and 1 (default: 0.5)
# yabai -m config split_ratio 0.5
#
# # set mouse interaction modifier key (default: fn)
# yabai -m config mouse_modifier fn
#
# # set modifier + left-click drag to move window (default: move)
# yabai -m config mouse_action1 move
#
# # set modifier + right-click drag to resize window (default: resize)
# yabai -m config mouse_action2 resize
#
# # set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
# yabai -m config focus_follows_mouse off
#
# # set mouse follows focus mode (default: off)
# yabai -m config mouse_follows_focus off
#
# # floating windows are always on top (default: off)
# yabai -m config window_topmost on
#
# # modify window shadows (default: on, options: on, off, float)
# # example: show shadows only for floating windows
# yabai -m config window_shadow float
#
# # window opacity (default: off)
# # example: render all unfocused windows with 90% opacity
# yabai -m config window_opacity on
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.7
#
# # add 20 padding to the top and 0 padding to the bottom of every space located on the main display
# yabai -m config external_bar main:10:0
# # add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
# yabai -m config external_bar all:10:10
